// Design-sync prepare step (cfg.buildCmd). The learner app is an Expo app, not a
// published library, so there is no dist/ for the converter to bundle. This
// mechanically derives the three build inputs it needs, all into the app's
// gitignored tmp/ (repo rule 10 — generated artifacts never land in tracked source,
// and nothing here is a hand-maintained second copy of the export surface):
//
//   tmp/ds/ds-entry.tsx  — the DS entry: `export *` over the app-owned UI boundary
//                          (src/ui) plus every src/components module, so the export
//                          surface tracks the source with no list to keep in sync.
//   tmp/ds/styles.css    — src/global.css compiled through the repo's own pinned
//                          Tailwind v4 toolchain (the utilities NativeWind emits on web).
//   tmp/ds/srcmap.json   — component → src path, printed for config drift checks.
//
// Run from the repo root: node .design-sync/prepare.mjs
import { createRequire } from "node:module";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const APP = join(REPO, "apps", "learner-app");
const SRC = join(APP, "src");
const OUT = join(APP, "tmp", "ds");
const require_ = createRequire(join(REPO, "package.json"));

mkdirSync(OUT, { recursive: true });

// ── 1. tokens.css is generated from tokens.js; metro.config.js regenerates it
// before Metro reads global.css, so a standalone Tailwind run must too.
const { generateLearnerTokenCss } = require_(join(REPO, "scripts", "generate-learner-token-css.cjs"));
generateLearnerTokenCss();

// ── 2. Component surface. PascalCase value exports per module; `export *` in the
// generated entry means the list below is only used for the srcmap + collision check.
const PASCAL_EXPORT = /^export\s+(?:function|const)\s+([A-Z][A-Za-z0-9]*)/gm;
const modules = [];
const byName = new Map();

function collect(relPath) {
  const abs = join(SRC, relPath);
  const text = readFileSync(abs, "utf8");
  const names = [...text.matchAll(PASCAL_EXPORT)].map((m) => m[1]);
  if (!names.length) return;
  modules.push({ relPath, names });
  for (const n of names) {
    if (byName.has(n)) {
      console.error(`✗ duplicate export ${n}: ${byName.get(n)} and ${relPath}`);
      process.exitCode = 1;
    }
    byName.set(n, relPath);
  }
}

// The app-owned UI boundary re-exports from its sibling modules under a curated
// set of public names (AppText is published as Text), so read the barrel's own
// export list rather than the implementation files behind it.
const uiBarrel = readFileSync(join(SRC, "ui", "index.ts"), "utf8");
const uiNames = [...uiBarrel.matchAll(/export\s*{([^}]*)}/g)]
  .flatMap((m) => m[1].split(","))
  .map((s) => s.trim())
  .filter((s) => s && !s.startsWith("type "))
  .map((s) => (s.includes(" as ") ? s.split(/\s+as\s+/)[1].trim() : s))
  .filter((n) => /^[A-Z][A-Za-z0-9]*$/.test(n));
for (const n of uiNames) byName.set(n, "ui/index.ts");
modules.push({ relPath: "ui/index.ts", names: uiNames, barrel: true });

for (const f of readdirSync(join(SRC, "components")).sort()) {
  if (!f.endsWith(".tsx") || f.includes(".test.")) continue;
  collect(join("components", f));
}

// ── 3. The entry. `export *` per module keeps the surface in lockstep with source.
const entry = `// GENERATED by .design-sync/prepare.mjs — do not edit, do not commit.
// Claude Design export surface for the learner app.
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { PortalHost } from "@rn-primitives/portal";
import { SafeAreaProvider } from "react-native-safe-area-context";
import type { ReactNode } from "react";

${modules.map((m) => `export * from "../../src/${m.relPath.replace(/\.tsx?$/, "")}";`).join("\n")}

// Preview fixture helpers. The map/formation components take projection view-models
// (TrailView, StudySession), and hand-written literals would be fragile fakes that rot.
// These are the repo's OWN builders — the same pair every component test uses — so
// preview cards compose from real projection output. Underscore-prefixed so they are
// not PascalCase components and read as scaffolding, not design vocabulary.
export { sessionFixture as __previewSessionFixture } from "../../src/learn/sessionFixture";
export { buildTrailView as __previewBuildTrailView } from "@lrnki/application/projection";

const previewQueryClient = new QueryClient({
  defaultOptions: { queries: { retry: false, refetchOnWindowFocus: false } }
});

/** Mirrors the learner app's real root layout (src/app/_layout.tsx): safe-area
 * metrics, the query client, and the portal host every Dialog/BottomSheet mounts
 * into. Components read all three from context, so previews wrap in this. */
export function DesignSystemProvider({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <SafeAreaProvider>
      <QueryClientProvider client={previewQueryClient}>
        {children}
        <PortalHost />
      </QueryClientProvider>
    </SafeAreaProvider>
  );
}
`;
writeFileSync(join(OUT, "ds-entry.tsx"), entry);

// ── 4. srcmap for config drift checks.
const srcmap = Object.fromEntries(
  [...byName.entries()]
    .filter(([, rel]) => rel !== "ui/index.ts")
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, rel]) => [name, `src/${rel}`])
);
for (const n of uiNames) srcmap[n] = uiSrcPath(n);
writeFileSync(join(OUT, "srcmap.json"), JSON.stringify(sortKeys(srcmap), null, 2) + "\n");

function uiSrcPath(name) {
  for (const f of readdirSync(join(SRC, "ui"))) {
    // .ts as well as .tsx — motion.ts exports AnimatedView.
    if (!/\.tsx?$/.test(f) || f.includes(".test.") || f === "index.ts") continue;
    const text = readFileSync(join(SRC, "ui", f), "utf8");
    // The barrel publishes AppText as Text; match the implementation name too.
    if (new RegExp(`^export\\s+(?:function|const)\\s+(?:${name}|App${name})\\b`, "m").test(text)) {
      return `src/ui/${f}`;
    }
  }
  return `src/ui/index.ts`;
}
function sortKeys(o) {
  return Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
}

// ── 5. Named prop types, so the emitted <Name>.d.ts is a real contract.
// The converter resolves props by finding a `<Name>Props` interface/alias in the
// package's .d.ts tree; these components declare their props inline
// (`Readonly<{…}>` in the parameter), and an Expo app ships no .d.ts tree at all,
// so every component would emit `{ [key: string]: unknown }`. This names each one
// via React's own ComponentProps so the TypeScript checker resolves the real
// structural shape — nothing is transcribed by hand, so nothing can drift.
//
// dist/types is a findTypesRoot candidate that is BOTH gitignored and excluded by
// the app's tsconfig, so this never enters `pnpm typecheck`.
const TYPES_OUT = join(APP, "dist", "types");
mkdirSync(TYPES_OUT, { recursive: true });
const componentNames = Object.keys(srcmap).filter((n) => n !== "MOTION");
const propsDts = `// GENERATED by .design-sync/prepare.mjs — do not edit, do not commit.
import type { ComponentProps } from "react";

type Entry = typeof import("../../tmp/ds/ds-entry");

${componentNames.map((n) => `export type ${n}Props = ComponentProps<Entry[${JSON.stringify(n)}]>;`).join("\n")}
`;
writeFileSync(join(TYPES_OUT, "ds-props.d.ts"), propsDts);

// ── 6. Compile global.css with the repo's pinned Tailwind v4 (same utilities the
// NativeWind web export emits). postcss + @tailwindcss/postcss are the repo's own.
const postcss = require_("postcss");
const tailwind = require_("@tailwindcss/postcss");
const cssIn = join(SRC, "global.css");
// `base` pins Tailwind v4's automatic source detection to the app, matching what
// Metro does. Without it the scan starts at cwd and sweeps the whole monorepo,
// emitting utilities from docs/fixtures the app never renders.
const compiled = await postcss([tailwind({ base: APP })]).process(readFileSync(cssIn, "utf8"), {
  from: cssIn,
  to: join(OUT, "styles.css"),
});
writeFileSync(join(OUT, "styles.css"), compiled.css);

console.error(`prepare: ${Object.keys(srcmap).length} components, entry + styles.css (${compiled.css.length} bytes) → ${OUT}`);
